---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creates a DynamoDB table with partition key as date, enables DynamoDB stream, connects Notify Lambda trigger, and EC2 instance for redash'
Resources:
  NotifyFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: 'Function to notify of changes'
      FunctionName: 'NotifyUpdateFunction'
      Code:
        S3Bucket: 'event-driven-python-aws-code'
        S3Key: 'index.js.zip'
        S3ObjectVersion: 'BVvzDmxztgj1I9RmPBoSzjoz7qlCzyfM' #Change this when making updates to code
      Handler: index.handler
      Role: 'arn:aws:iam::018943110893:role/LambdaFullAccess'
      Runtime: nodejs12.x
      Timeout: 300
      Tags: 
        - Key: 'Project'
          Value: 'Event-Driven Python'
  ONTARIOCOVIDDATA:
    Type: 'AWS::DynamoDB::Table'
    Properties: 
      AttributeDefinitions: 
        - AttributeName: 'Date'
          AttributeType: 'S'
      BillingMode: 'PAY_PER_REQUEST'
      KeySchema: 
        - AttributeName: 'Date'
          KeyType: 'HASH'
      TableName: 'ONTARIOCOVIDDATA'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags: 
        - Key: 'Project'
          Value: 'Event-Driven Python'
  DataTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn:
        Fn::GetAtt: [ ONTARIOCOVIDDATA , StreamArn ]
      FunctionName:
        Fn::GetAtt: [ NotifyFunction , Arn ]
      StartingPosition: LATEST
  RedashInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0d915a031cabac0e0'
      InstanceType: 't2.small'
      KeyName: 'Chandy'
      Tags:
        - Key: 'Project'
          Value: 'Event-Driven Python'