AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing lambda python function for Event-Driven-Python-AWS project.
Resources:
  dataETL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./dataETL/
      Description: 'Python function to extract data from source and load to DynamoDB'
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::018943110893:role/LambdaFullAccess'
      Tags:
        Key: "project"
        Value: "Event-Driven-Python-AWS"
      Events:
        dailyCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 * * ? *) #run at 11am everyday
            Name: DailyCheck
            Description: Scheduled event to run at 11am (15:00 GMT) everyday
            Enabled: True
