---
AWSTemplateFormatVersion: "2010-09-09"

Description: 'Creates a DynamoDB table with partition key as date'

Resources:
  USCOVIDDATA:
    Type: 'AWS::DynamoDB::Table'
    Properties: 
      AttributeDefinitions: 
        - AttributeName: 'Date'
          AttributeType: 'S'
      BillingMode: 'PAY_PER_REQUEST'
      KeySchema: 
        - AttributeName: 'Date'
          KeyType: 'HASH'
      TableName: 'USCOVIDDATA'
      Tags: 
        - Key: 'Project'
          Value: 'Event-Driven Python'